/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "zeiptnyxcbnnfpgxlqqj"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplaXB0bnl4Y2JubmZwZ3hscXFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc5NDQ3ODYsImV4cCI6MjA4MzUyMDc4Nn0.Y-8Ia__ai9T-HDq-uDbXMyyXpYhxTA-KHwHXRxAdZFk"